### PR TITLE
Remove kinda useless comment on all of the bypass

### PR DESCRIPTION
**Pull request by GetRektBoy724**
For the rasta-mouse ASB Bypass,it get triggered by AMSI just because of the comment :')
image

### CODE REVIEW

**Comment by GetRektBoy724** [comment]
i personally never encounter this but one of my friends did so...

**Comment by Flangvik** [comment]
Hey, so the comments are totally useless, sorta...
I use it as a lazy filter, so people that have "no idea" what they are doing can't abuse AMSI.fail heavily.
(Since the comments have signatures) So for now I'm actually going to leave them in ;)

**Comment by GetRektBoy724** [comment]
> Hey, so the comments are totally useless, sorta...
> I use it as a lazy filter, so people that have "no idea" what they are doing can't abuse AMSI.fail heavily.
> (Since the comments have signatures) So for now I'm actually going to leave them in ;)

Ahh yea ok,i actually have no problem at all,i can parse out the output from the AMSI.fail with powershell to remove the comment :)

**Comment by GetRektBoy724** [comment]
And sorry for the disturb,my friend only need to reinstall his Windows VM and everything works fine again 😂

**Pull request closed without merging**
